### DISCUSSION TITLE
On appending -r htmlextra didnot work via github action

### DISCUSSION THREAD

**Discussion by BhuwanPandey** [DannyDainton/newman-reporter-htmlextra#429] [Q&A]
Hy there,

github actions looks like

```

jobs:
  tester:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      # Install Node on the runner
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Install the newman command line utility and also install the html extra reporter
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      # Make directory to upload the test results
      - name: Make Directory for results
        run: mkdir -p result
      
      # Run the POSTMAN collection
      - name: Run POSTMAN collection
        run: |
          newman run https://api.getpostman.com/collections/${{ secrets.COLLECTION_ID }}?apikey=${{ secrets.API_KEY }} -e https://api.getpostman.com/environments/${{ secrets.ENVIRONMENT }}?apikey=${{ secrets.API_KEY }} -r htmlextra --reporter-htmlextra-export result/report.html

      # Upload the contents of Test Results directory to workspace
      - name: Output the run Details
        uses: actions/upload-artifact@v2
        with: 
          name: RunReports
          path: result
```

 **OUTPUT:**
           ❌  Failure - Main Run POSTMAN collection
            exitcode '1': failure

When I run above github action , it didnot work but after removing ( -r htmlextra --reporter-htmlextra-export result/report.html)
these part from above , it's working.
**Installed packed while running GITHUB ACTIONS**

```
| ├── corepack@0.23.0
| ├── newman-reporter-htmlextra@1.23.0
| ├── newman@6.1.0
| └── npm@10.2.4
```

And,
In the command prompt, above code working . I don't know what things create the problem. Can somebody help me to trackle this problem.
