### ISSUE TITLE
Report not generated when running the reporter using CircleCI

### ISSUE THREAD

**Issue by ferpioli** [DannyDainton/newman-reporter-htmlextra#264]
in my yml I have the following steps

 - run:
            name: Teste post test e2e       
            command: |
              cd ~/homologacao_automatizada/request
              npm uninstall -g newman newman-reporter-htmlextra
              npm install -g newman newman-reporter-htmlextra
              newman run teste-e2e.postman_collection.json -e test-e2e.postman_environment.json -d cenariospostRequest.json --delay-request 2000 -r cli,htmlextra --reporter-htmlextra-title "cenarios Request e2e "

                     
      - store_artifacts:
          path: ~/homologacao_automatizada/request/newman

**Comment by DannyDainton** [comment]
I don't even know what version you're using?

There's a reason why I created a bug template and asked that all the details be filled in. 😂

**Comment by DannyDainton** [comment]
Whatever report is created, it's creating that in the default `./newman` directory as you haven't specified any path using the `--reporter-htmlextra-export` flag.

Where does it create your report locally?

**Comment by ferpioli** [comment]
sorry where i see the version, am i new to this?

**Comment by ferpioli** [comment]
but if I remove the flag it generates normal, it seems that it does not recognize the flag when I put the flag --reporter-htmlextra-logs it does not generate the log so I think it can be version

**Comment by DannyDainton** [comment]
I don't really understand what you mean, you keep flipping between talking about different flags.

Can you share some images of what you're seeing please.

**Comment by ferpioli** [comment]
The error occurs only when I rotate the circleCi, passing
newman run request-e2e.postman_collection.json -e request-e2e.postman_environment.json -d scenariospostRequestKafka.json --delay-request 2000 -r cli, htmlextra --reporter-htmlextra-title

if I pass the command line like this

  newman run request-e2e.postman_collection.json -e request-e2e.postman_environment.json -d scenariospostRequestKafka.json --delay-request 2000 -r cli, htmlextra

it works

+ newman@5.1.2
+ newman-reporter-htmlextra@1.19.0

**Comment by DannyDainton** [comment]
I used CircleCI like this and can see the title in the artefact:

```yml
version: 2.1
jobs:
  build:
    docker:
      - image: dannydainton/htmlextra
    steps:
      - checkout
      - run:
         command: |
           mkdir -p ~/test-results/newman
           newman run ./tests/Restful_Booker_Collection.postman_collection.json -e ./tests/Restful_Booker_Environment.postman_environment.json -r cli,htmlextra --reporter-htmlextra-title "Restful Booker"
           cp ./newman/*.html ~/test-results/newman/
      - store_artifacts:
          path: ~/test-results/newman
```

![Screenshot 2020-09-01 at 09 33 38](https://user-images.githubusercontent.com/17089546/91827097-506e0c80-ec36-11ea-9bd3-d3352f41c3cb.png)
