### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by danielferromeral** [DannyDainton/newman-reporter-htmlextra#340]
**Is your feature request related to a problem? Please describe.**
I run newman in a docker-compose, with two environment variables (the tags with the version of other two services inside the docker compose).
```yml
postman-newman:
    networks:
      - conector
    restart: on-failure
    build:
      context: ./postman
      dockerfile: Dockerfile
    command: [ "sh /etc/scripts/run-postman-test.sh" ]
    volumes:
      - ./postman/scripts:/etc/scripts
      - ./postman/tests:/etc/newman
    environment:
      SEARCH_VERSION: ${SEARCH_VERSION}
      INDEXER_VERSION: ${INDEXER_VERSION}
```
The docker compose calls a script that runs newman.
```bash
printf "Search Version: "
printenv SEARCH_VERSION
printf "Indexer Version: "
printenv INDEXER_VERSION
newman run /etc/newman/BasicTestCollection.json -d /etc/newman/BasicUCData.json -e /etc/newman/environment.json -g /etc/newman/global.json -r htmlextra --reporter-htmlextra-showEnvironmentData --reporter-htmlextra-showGlobalData --reporter-htmlextra-showFolderDescription --reporter-htmlextra-logs --reporter-htmlextra-timezone "Spain/Madrid" --reporter-htmlextra-browserTitle "RegressionTest" --reporter-htmlextra-title "RegressionTest" --reporter-htmlextra-export ./reports/report.html --reporter-htmlextra-template ./report-template.hbs
```
(Off-topic: the timezone doesnt work, it still appears in the reports as two hours ago, should be 11:00, but appears 9:00)

I need the two env vars inside the reports (to know what version of the services was run in the test), so I made a custom template using the one of htmlextra as source code, adding these lines inside the "File information" box.
```hbs
{{#if process.env.INDEXER_VERSION}}<span><i class="fas fa-file-code"></i></span><strong> Indexer Version:</strong> {{process.env.INDEXER_VERSION}}<br>{{/if}}
{{#if process.env.SEARCH_VERSION}}<span><i class="fas fa-file-code"></i></span><strong> Search Version:</strong> {{process.env.SEARCH_VERSION}}<br>{{/if}}
```
But it doesn't appear.

**Describe the solution you'd like**
I would like that you would have a flag to show the env vars inside the (in my case) container, and not only the ones that is using newman, something like --showEnvVar.
Or a flag to add extra info, --extraInfo "Indexer Version: ${INDEXER_VERSION} \n Search Version: ${SEARCH_VERSION}"

**Describe alternatives you've considered**
I guess I could sent that tags as title, and then using the title field, trim it to get the tags back. I also tried using a sed commando to update the document, but didn't work.

**Additional context**
This docker compose is part of jenkins pipeline. When a change happens to the repo, the jenkins trigger the docker compose, deploying everything.
